name: Deploy to Azure Web Apps

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: your-app-name # Replace with your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Path to your web app project (default is repository root)
  NODE_VERSION: '20.x' # Node.js version to use

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install dependencies
        run: npm install
      
      - name: Build the application
        run: npm run build
      
      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
